CREATE USER django WITH PASSWORD 'django';
CREATE USER fastapi WITH PASSWORD 'fastapi';
CREATE USER flask WITH PASSWORD 'flask';
CREATE USER express WITH PASSWORD 'express';
CREATE USER fastify WITH PASSWORD 'fastify';
CREATE USER gingorm WITH PASSWORD 'gingorm';

GRANT CONNECT ON DATABASE benchmark_db TO django;
GRANT ALL PRIVILEGES ON DATABASE benchmark_db TO django;
GRANT ALL PRIVILEGES ON SCHEMA public TO django;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO django;

GRANT CONNECT ON DATABASE benchmark_db TO fastapi;
GRANT ALL PRIVILEGES ON DATABASE benchmark_db TO fastapi;
GRANT ALL PRIVILEGES ON SCHEMA public TO fastapi;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fastapi;

GRANT CONNECT ON DATABASE benchmark_db TO flask;
GRANT ALL PRIVILEGES ON DATABASE benchmark_db TO flask;
GRANT ALL PRIVILEGES ON SCHEMA public TO flask;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO flask;

GRANT CONNECT ON DATABASE benchmark_db TO express;
GRANT ALL PRIVILEGES ON DATABASE benchmark_db TO express;
GRANT ALL PRIVILEGES ON SCHEMA public TO express;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO express;

GRANT CONNECT ON DATABASE benchmark_db TO fastify;
GRANT ALL PRIVILEGES ON DATABASE benchmark_db TO fastify;
GRANT ALL PRIVILEGES ON SCHEMA public TO fastify;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fastify;

GRANT CONNECT ON DATABASE benchmark_db TO gingorm;
GRANT ALL PRIVILEGES ON DATABASE benchmark_db TO gingorm;
GRANT ALL PRIVILEGES ON SCHEMA public TO gingorm;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gingorm;


